services:
  echo-flask:
    build: .
    container_name: echo-flask
    ports:
      - "5001:5000"
    environment:
      - APP_NAME=${APP_NAME:-echo-flask}
    networks:
      - atp-network
    restart: unless-stopped

networks:
  atp-network:
    external: true
